---
title: "Cell type marker expression for renal corpuscle and tubule populations"
author: "Javier Perales-Paton - javier.perales@bioquant.uni-heidelberg.de"
license: "GPL-v3"
output: github_document
---

```{r setup, include=FALSE}
Sys.setenv(RSTUDIO_PANDOC="/usr/lib/rstudio/bin/pandoc")
knitr::opts_chunk$set(echo = TRUE)

# Output directory
OUTDIR <- "./RCorpuscleTubule/"
if(!dir.exists(OUTDIR)) dir.create(OUTDIR);
# Figures
FIGDIR <- paste0(OUTDIR, "/figures/")
knitr::opts_chunk$set(fig.path=FIGDIR)
knitr::opts_chunk$set(dev=c('png', 'pdf'))
# Data
DATADIR <- paste0(OUTDIR, "/data/")
if(!dir.exists(DATADIR)) dir.create(DATADIR);
```


## Load libraries and auxiliar functions

```{r libs}
set.seed(1234)
suppressPackageStartupMessages(require(Seurat))
suppressPackageStartupMessages(require(ggplot2))
suppressPackageStartupMessages(require(cowplot))
suppressPackageStartupMessages(require(ComplexHeatmap))
suppressPackageStartupMessages(require(GSEABase))
source("../src/seurat_fx.R")
```

# Organoids

## Load SeuratObject with initial clustering outcome
```{r load_SeuratObjects}
list_rds <- c("CK5_organoid"="../Individual_analysis_CK5_early_organoid/output/4_final_assignment/data/SeuratObject.rds",
	      "CK119_organoid"="../Individual_analysis_CK119_late_organoid/output/4_final_assignment/data/SeuratObject.rds",
	      "JX1_HC_organoid"="../Individual_analysis_JX1_HC_organoid/output/4_final_assignment/data/SeuratObject.rds",
	      "JX2_PKD1KO_organoid"="../Individual_analysis_JX2_PKD1KO_organoid/output/4_final_assignment/data/SeuratObject.rds",
	      "JX3_PKD2KO_organoid"="../Individual_analysis_JX3_PKD2KO_organoid/output/4_final_assignment/data/SeuratObject.rds",
	      "CK120_CD13"="../Individual_analysis_CK120_CD13/output/4_final_assignment/data/SeuratObject.rds",
	      "CK121_CD24"="../Individual_analysis_CK121_CD24/output/4_final_assignment/data/SeuratObject.rds")

# Load individual SeuratObjects
for(sname in names(list_rds)) {
  cat(paste0("Loading ",sname, "'s SeuratObject","\n"), file=stdout())
  SObj <- readRDS(list_rds[[sname]])
  # Scale data
  SObj <- ScaleData(SObj, verbose = FALSE)
  
  SObj$proj_ident <- paste0("[",Project(SObj),"] ",Idents(SObj))
  SObj$ident_proj <- paste0(Idents(SObj), " [",Project(SObj),"]")
  # Rename idents incl
  assign(sname, SObj)
  rm(SObj)
}

(snames <- names(list_rds))
```


# Merged-sample report
```{r merge}
# Merge ind
S<- merge(x=get(x = snames[1]), y=sapply(snames[-1], get), add.cell.ids = snames)
# Clean mem
rm(list = snames)
```

## Gene Set Collection

```{r}
# GSC <- getGmt("../data/Prior/celltypes_RenalcorpuscleTubule_KPMP.gmt")
# genes <- unlist(geneIds(GSC))
```

## Heatmap

```{r load_colors}
cols <- readRDS(file="./output/color_scheme.rds")
```

```{r 10_CellTypeRenalCorpuscleRK_sortedCells, fig.width=9.4, fig.height=9, dpi=600, warning=FALSE}
# Gene Set collection
GSC <- getGmt("../data/Prior/celltypes_RK_sorted.gmt")
genes <- unlist(geneIds(GSC))

# Selected samples
samples_sel <- c("CK120_CD13", "CK121_CD24")

# Subset cells
Sx<- S[intersect(rownames(S), genes), S$orig.ident %in% samples_sel]
Sx<- ScaleData(Sx, verbose = FALSE)

# Heatmaps
CK120_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK120_CD13"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

CK121_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK121_CD24"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

draw(CK120_hp + CK121_hp, ht_gap = unit(10, "mm"), 
    column_title = "sorted CD13+ and CD24+ cells", 
    column_title_gp = gpar(fontsize = 16))

```

```{r 10_CellTypeRenalCorpuscleRK_organoids, fig.width=11, fig.height=10, dpi=600, warning=FALSE}
# Gene Set collection
GSC <- getGmt("../data/Prior/celltypes_RK_organoids.gmt")
genes <- unlist(geneIds(GSC))

# Selected samples
samples_sel <- c("CK5_organoid", "CK119_organoid", "JX1_HC_organoid")

# Subset cells
Sx<- S[intersect(rownames(S), genes), S$orig.ident %in% samples_sel]
Sx<- ScaleData(Sx, verbose = FALSE)

# Heatmaps
CK5_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK5_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

CK119_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK119_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

JX1_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="JX1_HC_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)



draw(CK5_hp + CK119_hp + JX1_hp, ht_gap = unit(10, "mm"), 
    column_title = "Early, late and Clevers organoids", 
    column_title_gp = gpar(fontsize = 16))
```

```{r 10_CellTypeRenalCorpuscleRKSuplements_SortedOrganoids, fig.width=18, fig.height=10, dpi=600, warning=FALSE}
# Gene Set collection
GSC <- getGmt("../data/Prior/celltypes_RK_supplements.gmt")
genes <- unlist(geneIds(GSC))

Sx <- S[intersect(rownames(S), genes), ]
Sx<- ScaleData(Sx, verbose = FALSE)
 
# Heatmaps
CK120_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK120_CD13"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

CK121_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK121_CD24"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

CK5_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK5_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

CK119_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK119_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

JX1_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="JX1_HC_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

JX2_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="JX2_PKD1KO_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

JX3_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="JX3_PKD2KO_organoid"),
		row_names_fontisze=8,
           res=NULL, cols=cols,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)



draw(CK120_hp + CK121_hp + CK5_hp + CK119_hp + JX1_hp + JX2_hp + JX3_hp, 
    column_title = "sorted CD13+, sorted CD24+, Early, late and Clevers organoids", 
     ht_gap = unit(10, "mm"), 
    column_title_gp = gpar(fontsize = 16))

```


# Tissue samples

## Load SeuratObject with initial clustering outcome
```{r load_SeuratObjects2}
list_rds <- c("CK224_PT25_PKD2-"="../Individual_analysis_CK224_PT25_PKD2-/output/2_cell_assignment/data/SeuratObject.rds",
	      "CK225_PT8_PKD1-"="../Individual_analysis_CK225_PT8_PKD1-/output/2_cell_assignment/data/SeuratObject.rds",
	      "ADPKD3"="../Individual_analysis_ADPKD3/output/2_cell_assignment/data/SeuratObject.rds",
	      "Control1"="../Individual_analysis_Control1/output/2_cell_assignment/data/SeuratObject.rds",
	      "Control2"="../Individual_analysis_Control2/output/2_cell_assignment/data/SeuratObject.rds")

# Load individual SeuratObjects
for(sname in names(list_rds)) {
  cat(paste0("Loading ",sname, "'s SeuratObject","\n"), file=stdout())
  SObj <- readRDS(list_rds[[sname]])
  # Scale data
  SObj <- ScaleData(SObj, verbose = FALSE)
  
  SObj$proj_ident <- paste0("[",Project(SObj),"] ",Idents(SObj))
  SObj$ident_proj <- paste0(Idents(SObj), " [",Project(SObj),"]")
  # Rename idents incl
  assign(sname, SObj)
  rm(SObj)
}

(snames <- names(list_rds))
```


# Merged-sample report
```{r merge2}
# Merge ind
S<- merge(x=get(x = snames[1]), y=sapply(snames[-1], get), add.cell.ids = snames)
# Clean mem
rm(list = snames)
```

```{r 10_CellTypeRenalCorpuscleRKSuplements_tissue, fig.width=18, fig.height=10, dpi=600, warning=FALSE}
# Gene Set collection
GSC <- getGmt("../data/Prior/celltypes_RK_supplements.gmt")
genes <- unlist(geneIds(GSC))

#NOTE: This is whole tissue, shall we scaled across samples when within sample is
# 	heterogeneous enough??
Sx <- S[intersect(rownames(S), genes), ]
Sx<- ScaleData(Sx, verbose = FALSE)
 
# Heatmaps
CK224_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK224_kidney_PKD2-"),
		row_names_fontisze=8,
           res=NULL,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

CK225_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="CK225_kidney_PKD1-"),
		row_names_fontisze=8,
           res=NULL,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

ADPKD3_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="ADPKD3_kidney"),
		row_names_fontisze=8,
           res=NULL,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

Control1_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="Control1_kidney"),
		row_names_fontisze=8,
           res=NULL,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)

Control2_hp <- DoHeatmap2(SeuratObject = subset(Sx, orig.ident=="Control2_kidney"),
		row_names_fontisze=8,
           res=NULL,
           assay="RNA", width = unit(41,"mm"),name="",
           show_hr = FALSE,
	   row_gap_mm = 0,
	   border_boolean=FALSE,
           GSC=GSC)



draw(Control1_hp + Control2_hp + CK224_hp + CK225_hp + ADPKD3_hp, ht_gap = unit(10, "mm"), 
    column_title = "Control1, Control2, CK224, CK225, ADPKD3", 
    column_title_gp = gpar(fontsize = 16))

```


